const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');
(async()=>{const b=await chromium.launch();const c=await b.newContext({viewport:{width:390,height:844}});const p=await c.newPage();p.on('dialog',d=>d.accept());const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.argv[2]||'http://localhost:8766/upgrade/');await p.evaluate(()=>document.fonts.ready);
const nav=async t=>p.locator(`nav [data-tab="${t}"]`).click();const state=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('jiwoo-words/upgrade/v2')));
await p.locator('[data-study-kind="4"]').click();const start=await p.locator('[data-action="start-study"]').boundingBox();assert.ok(start.y+start.height<650);await p.locator('[data-action="start-study"]').click();assert.ok(await p.evaluate(()=>{const s=JSON.parse(localStorage.getItem('jiwoo-words/upgrade/v2'));return s.session.queue.every(id=>window.JIWOO_CARDS.find(c=>c.id===id).g===4)}));
await p.locator('[data-action="reveal"]').click();await p.evaluate(()=>{window.spoken=[];speechSynthesis.speak=u=>window.spoken.push({text:u.text,rate:u.rate});});await p.locator('.word-row [data-speak]').click();await p.locator('.example-actions [data-speak]').click();let sounds=await p.evaluate(()=>window.spoken);assert.equal(sounds.length,2);assert.ok(sounds[1].text.length>sounds[0].text.length);assert.ok(!/[{}]/.test(sounds[1].text));assert.ok(Math.abs(sounds[0].rate-.85)<.0001);
await p.reload();assert.equal(await p.locator('[data-study-kind="4"]').getAttribute('aria-pressed'),'true');assert.ok(await p.locator('[data-mark="yes"]').count());
await nav('quiz');assert.equal(await p.locator('[data-action="challenge"]').count(),0);for(const type of ['spell','cloze','match']){await p.locator(`[data-game="${type}"]`).click();const s=await state();assert.ok(s.game.list.length>0);await p.locator('[data-action="game-menu"]').click();}
await nav('settings');assert.equal(await p.locator('[data-pref="speechRate"]').inputValue(),'0.85');await p.locator('[data-pref="speechRate"]').selectOption('0.65');assert.equal(await p.locator('[data-pref="speechRate"]').inputValue(),'0.65');assert.ok(await p.locator('[data-pref="speechRate"]').evaluate(e=>e===document.activeElement));await p.locator('[data-pref="theme"]').selectOption('dark');assert.equal(await p.locator('html').getAttribute('data-theme'),'dark');
await nav('library');await p.locator('[data-filter="grade"]').selectOption('4');await p.locator('.library-item summary').first().click();assert.equal(await p.locator('.library-item[open] [data-speak]').count(),2);assert.ok(await p.locator('.library-item[open] .expand-cue').count());
for(const width of [320,390,430,1280]){await p.setViewportSize({width,height:844});for(const tab of ['study','quiz','library','records','settings']){await nav(tab);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${width} ${tab} overflow`);for(const item of await p.locator('nav button').all()){const r=await item.boundingBox();assert.ok(r.height>=44&&r.width>=44);}}}
await p.setViewportSize({width:390,height:500});await nav('quiz');await p.locator('[data-game="spell"]').click();await p.locator('#quiz-answer').fill('test');await p.locator('#answer-form button').click();await p.locator('[data-action="next-question"]').click();assert.equal((await state()).game.idx,1);assert.equal(await p.locator('#quiz-answer').getAttribute('enterkeyhint'),'done');
await p.evaluate(async()=>{await navigator.serviceWorker.ready;});await p.waitForFunction(()=>navigator.serviceWorker.controller);await c.setOffline(true);await p.reload();assert.equal(await p.evaluate(async()=>{const r=await fetch('./header-magic.svg');return r.ok;}),true);assert.deepEqual(errors,[]);console.log('PASS: mobile entry, idiom discovery, resume, word/sentence speech wiring, game routes, saved voice speed, focus, library disclosure, 4 widths, dark mode, short viewport, offline decoration');await b.close();})().catch(e=>{console.error(e);process.exit(1)});
